---

extends:
  - airbnb
  - "plugin:jest/recommended"

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

settings:
  import/resolver:
    - node
    - webpack

rules:
  import/extensions: 0
  react/prop-types: 0
  no-console: 0
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/click-events-have-key-events: 0
